packages:
  - artifacts/*
  - lib/*
  - lib/integrations/*
  - scripts

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/node': ^22.0.0
  drizzle-orm: ^0.45.2
  tsx: ^4.21.0
  zod: ^3.25.76

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

overrides:
  esbuild: "0.27.3"
